#!/bin/sh
set -eu

# Coolify injects application-wide variables into every Compose service. User
# Skill processes share this container's PID namespace, so rebuilding only the
# child environment is insufficient: they can inspect /proc/1/environ. Replace
# PID 1 with a process whose initial environment contains Runner-only values.
mkdir -p /tmp/skill-home

exec env -i \
  "PATH=${PATH:-/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin}" \
  "HOME=/tmp/skill-home" \
  "LANG=${LANG:-C.UTF-8}" \
  "LC_ALL=${LC_ALL:-}" \
  "TZ=${TZ:-}" \
  "SSL_CERT_FILE=${SSL_CERT_FILE:-}" \
  "SSL_CERT_DIR=${SSL_CERT_DIR:-}" \
  "PIP_INDEX_URL=${PIP_INDEX_URL:-}" \
  "PIP_TRUSTED_HOST=${PIP_TRUSTED_HOST:-}" \
  "PIP_DEFAULT_TIMEOUT=${PIP_DEFAULT_TIMEOUT:-}" \
  "PIP_RETRIES=${PIP_RETRIES:-}" \
  "NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY:-}" \
  "NPM_CONFIG_FETCH_RETRIES=${NPM_CONFIG_FETCH_RETRIES:-}" \
  "NPM_CONFIG_FETCH_RETRY_MINTIMEOUT=${NPM_CONFIG_FETCH_RETRY_MINTIMEOUT:-}" \
  "NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT=${NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT:-}" \
  "NPM_CONFIG_FETCH_TIMEOUT=${NPM_CONFIG_FETCH_TIMEOUT:-}" \
  "NODE_PATH=${NODE_PATH:-/opt/skill-node/node_modules}" \
  "PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE:-1}" \
  "PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}" \
  "SOURCE_COMMIT=${SOURCE_COMMIT:-unknown}" \
  "SKILL_RUNNER_TOKEN=${SKILL_RUNNER_TOKEN:-}" \
  "SKILL_CACHE_ROOT=${SKILL_CACHE_ROOT:-/cache}" \
  "SKILL_BASE_NODE_MODULES=${SKILL_BASE_NODE_MODULES:-/opt/skill-node/node_modules}" \
  "SKILL_RUNNER_MAX_CONCURRENCY=${SKILL_RUNNER_MAX_CONCURRENCY:-4}" \
  "SKILL_RUNNER_MAX_QUEUE=${SKILL_RUNNER_MAX_QUEUE:-100}" \
  "SKILL_RUNNER_QUEUE_WAIT_SECONDS=${SKILL_RUNNER_QUEUE_WAIT_SECONDS:-300}" \
  "SKILL_RUNNER_OFFICE_CONCURRENCY=${SKILL_RUNNER_OFFICE_CONCURRENCY:-1}" \
  "SKILL_PACKAGE_MAX_BYTES=${SKILL_PACKAGE_MAX_BYTES:-104857600}" \
  "SKILL_PACKAGE_EXPANDED_MAX_BYTES=${SKILL_PACKAGE_EXPANDED_MAX_BYTES:-524288000}" \
  "SKILL_PACKAGE_MAX_FILES=${SKILL_PACKAGE_MAX_FILES:-1000}" \
  "SKILL_CACHE_RETENTION_SECONDS=${SKILL_CACHE_RETENTION_SECONDS:-604800}" \
  "SKILL_CACHE_MAX_BYTES=${SKILL_CACHE_MAX_BYTES:-10737418240}" \
  "SKILL_FAILED_TEMP_RETENTION_SECONDS=${SKILL_FAILED_TEMP_RETENTION_SECONDS:-3600}" \
  "STORAGE_GATEWAY_URL=${STORAGE_GATEWAY_URL:-}" \
  "STORAGE_PROJECT_TOKEN=${STORAGE_PROJECT_TOKEN:-}" \
  "STORAGE_GATEWAY_TIMEOUT_SECONDS=${STORAGE_GATEWAY_TIMEOUT_SECONDS:-60}" \
  "$@"
