"""Least-privilege direct-ECS publishing into the ZhuoJian application catalog."""

from __future__ import annotations

import hashlib
import json
import secrets
from datetime import UTC, datetime
from urllib.parse import urljoin, urlsplit
from uuid import UUID

from fastapi import HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.ecs_publisher_auth import STORED_PREFIX_LENGTH
from app.models.ecs_runtime import EcsModuleRelease, EcsRuntime
from app.models.enterprise_application import EnterpriseApplication
from app.models.organization import Organization
from app.schemas.ecs_publisher import EcsModulePublishInput, EcsRuntimeCreate
from app.schemas.enterprise_application import (
    EnterpriseApplicationCreate,
    EnterpriseApplicationIntegrationInput,
    EnterpriseApplicationUpdate,
)
from app.services import enterprise_application_service, subsystem_integration_service
from app.utils.crypto import hash_api_key
from app.utils.public_url import assert_public_http_url, same_origin


def _new_credential() -> tuple[str, str, str]:
    token = f"zjrt_{secrets.token_urlsafe(48)}"
    return token, token[:STORED_PREFIX_LENGTH], hash_api_key(token)


def runtime_profile(runtime: EcsRuntime, platform_url: str) -> dict:
    return {
        "schemaVersion": 2,
        "enterpriseKey": runtime.enterprise_key,
        "organizationId": str(runtime.organization_id),
        "environment": runtime.environment,
        "runtimeId": runtime.runtime_key,
        "deployment": {
            "provider": "direct-ecs",
            "repositoriesRoot": "/srv/zhuojian/repositories",
            "deploymentsRoot": "/srv/zhuojian/deployments",
            "dataRoot": "/srv/zhuojian/data",
            "backupsRoot": "/srv/zhuojian/backups",
            "nginxConfigRoot": "/etc/nginx/conf.d",
            "registrationCredentialRef": "/etc/zhuojian/runtime-registration.key",
        },
        "domains": {
            "suffix": runtime.domain_suffix,
            "httpsRequired": True,
        },
        "platform": {
            "baseUrl": platform_url.rstrip("/"),
            "registrationEndpoint": "/api/v1/ecs-publisher/modules/register",
            "registrationEnabled": runtime.is_active,
        },
    }


async def create_runtime(
    db: AsyncSession,
    organization: Organization,
    data: EcsRuntimeCreate,
) -> tuple[EcsRuntime, str]:
    existing = (
        await db.execute(
            select(EcsRuntime).where(
                EcsRuntime.organization_id == organization.id,
                EcsRuntime.runtime_key == data.runtime_key,
            )
        )
    ).scalar_one_or_none()
    if existing is not None:
        raise HTTPException(status_code=409, detail="ECS runtime key already exists")
    credential, prefix, digest = _new_credential()
    row = EcsRuntime(
        organization_id=organization.id,
        runtime_key=data.runtime_key,
        enterprise_key=data.enterprise_key,
        environment=data.environment,
        domain_suffix=data.domain_suffix,
        public_address=data.public_address,
        credential_prefix=prefix,
        credential_hash=digest,
        credential_rotated_at=datetime.now(UTC),
        is_active=True,
    )
    db.add(row)
    await db.flush()
    await db.refresh(row)
    return row, credential


async def list_runtimes(db: AsyncSession, organization_id: UUID | str) -> list[EcsRuntime]:
    return list(
        (
            await db.execute(
                select(EcsRuntime)
                .where(EcsRuntime.organization_id == UUID(str(organization_id)))
                .order_by(EcsRuntime.created_at)
            )
        ).scalars()
    )


async def get_runtime(
    db: AsyncSession, organization_id: UUID | str, runtime_id: UUID | str
) -> EcsRuntime | None:
    return (
        await db.execute(
            select(EcsRuntime).where(
                EcsRuntime.id == UUID(str(runtime_id)),
                EcsRuntime.organization_id == UUID(str(organization_id)),
            )
        )
    ).scalar_one_or_none()


async def rotate_credential(db: AsyncSession, runtime: EcsRuntime) -> str:
    credential, prefix, digest = _new_credential()
    runtime.credential_prefix = prefix
    runtime.credential_hash = digest
    runtime.credential_rotated_at = datetime.now(UTC)
    runtime.is_active = True
    await db.flush()
    # ``updated_at`` is generated by a server-side onupdate expression.  Refresh
    # before FastAPI/Pydantic serializes the ORM object to avoid async lazy IO.
    await db.refresh(runtime)
    return credential


async def set_runtime_active(db: AsyncSession, runtime: EcsRuntime, active: bool) -> EcsRuntime:
    runtime.is_active = active
    await db.flush()
    await db.refresh(runtime)
    return runtime


async def get_release(
    db: AsyncSession, organization_id: UUID | str, application_slug: str
) -> EcsModuleRelease | None:
    return (
        await db.execute(
            select(EcsModuleRelease).where(
                EcsModuleRelease.organization_id == UUID(str(organization_id)),
                EcsModuleRelease.application_slug == application_slug,
            )
        )
    ).scalar_one_or_none()


def _validated_base_url(runtime: EcsRuntime, application_slug: str, value: str) -> str:
    base_url = value.rstrip("/") + "/"
    try:
        assert_public_http_url(base_url, require_https=runtime.environment != "development")
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    parsed = urlsplit(base_url)
    expected_host = f"{application_slug}.{runtime.domain_suffix}"
    if parsed.hostname != expected_host:
        raise HTTPException(
            status_code=422,
            detail=f"base_url host must be '{expected_host}' for this ECS runtime",
        )
    if parsed.path not in {"", "/"} or parsed.query or parsed.fragment:
        raise HTTPException(status_code=422, detail="base_url must not contain a path, query or fragment")
    return base_url


def _manifest_digest(manifest: dict) -> str:
    canonical = json.dumps(
        manifest, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


async def _upsert_application(
    db: AsyncSession,
    runtime: EcsRuntime,
    release: EcsModuleRelease,
    data: EcsModulePublishInput,
) -> EnterpriseApplication:
    application = (
        await db.execute(
            select(EnterpriseApplication).where(
                EnterpriseApplication.organization_id == runtime.organization_id,
                EnterpriseApplication.slug == data.application_slug,
                EnterpriseApplication.deleted_at.is_(None),
            )
        )
    ).scalar_one_or_none()
    if application is not None and release.application_id and application.id != release.application_id:
        raise HTTPException(status_code=409, detail="Application slug is bound to another release")
    if application is not None and not same_origin(application.entry_url, release.base_url):
        if release.application_id is None:
            raise HTTPException(status_code=409, detail="Application slug uses a different origin")
    config = {
        "deploymentManaged": True,
        "deploymentProvider": "direct-ecs",
        "runtimeId": str(runtime.id),
        "runtimeKey": runtime.runtime_key,
        "sourceCommit": data.source_commit,
    }
    if application is None:
        application = await enterprise_application_service.create_application(
            db,
            UUID(str(runtime.organization_id)),
            EnterpriseApplicationCreate(
                name=data.application_name,
                slug=data.application_slug,
                description="由企业 AI 按灼见原生协议开发并部署在企业 ECS",
                entry_url=release.base_url,
                display_mode="embedded",
                is_active=True,
                assistant_enabled=True,
                assistant_config=config,
            ),
        )
    else:
        application = await enterprise_application_service.update_application(
            db,
            application,
            EnterpriseApplicationUpdate(
                name=data.application_name,
                entry_url=release.base_url,
                is_active=True,
                assistant_enabled=True,
                assistant_config={**(application.assistant_config or {}), **config},
            ),
        )
    return application


async def register_module(
    db: AsyncSession,
    runtime: EcsRuntime,
    data: EcsModulePublishInput,
) -> EcsModuleRelease:
    if not runtime.is_active:
        raise HTTPException(status_code=401, detail="ECS runtime credential is revoked")
    metadata_size = len(json.dumps(data.release_metadata, ensure_ascii=False).encode("utf-8"))
    if metadata_size > 64 * 1024:
        raise HTTPException(status_code=422, detail="release_metadata exceeds 64KB")
    base_url = _validated_base_url(runtime, data.application_slug, data.base_url)
    release = await get_release(db, runtime.organization_id, data.application_slug)
    if release is not None and release.runtime_id != runtime.id:
        previous_runtime = await db.get(EcsRuntime, release.runtime_id)
        if previous_runtime is not None and previous_runtime.is_active:
            raise HTTPException(
                status_code=409,
                detail="Module is bound to another active ECS runtime; deactivate it before migration",
            )
        release.runtime_id = runtime.id
    now = datetime.now(UTC)
    if release is None:
        release = EcsModuleRelease(
            organization_id=runtime.organization_id,
            runtime_id=runtime.id,
            application_slug=data.application_slug,
            application_name=data.application_name,
            base_url=base_url,
            requested_commit=data.source_commit.lower(),
            image_ref=data.image_ref,
            status="verifying",
            release_metadata=data.release_metadata,
            deployed_at=data.deployed_at or now,
            last_seen_at=now,
        )
        db.add(release)
    else:
        release.application_name = data.application_name
        release.base_url = base_url
        release.requested_commit = data.source_commit.lower()
        release.image_ref = data.image_ref
        release.status = "verifying"
        release.release_metadata = data.release_metadata
        release.last_error = None
        release.deployed_at = data.deployed_at or now
        release.last_seen_at = now
    await db.flush()

    try:
        discovery = await subsystem_integration_service.discover_subsystem(
            db, runtime.organization_id, base_url, data.integration_secret
        )
        manifest = discovery["manifest"]
        if discovery["suggested_slug"] != data.application_slug:
            raise ValueError("Manifest applicationSlug does not match the release")
        enterprise = manifest.get("enterprise") if isinstance(manifest, dict) else None
        if not isinstance(enterprise, dict) or enterprise.get("key") != runtime.enterprise_key:
            raise ValueError("Manifest enterprise.key does not match the ECS runtime")
        application = await _upsert_application(db, runtime, release, data)
        await subsystem_integration_service.configure_integration(
            db,
            application,
            EnterpriseApplicationIntegrationInput(
                manifest_url=urljoin(base_url, "/api/integration/manifest"),
                auth_token=data.integration_secret,
                sync_enabled=True,
            ),
        )
        sync = await subsystem_integration_service.sync_integration(db, application)
        if sync.get("status") != "healthy":
            raise ValueError(str(sync.get("detail") or "Manifest synchronization failed"))
        release.application_id = application.id
        release.contract_revision = str(manifest.get("contractRevision") or "2.0")
        release.manifest_digest = _manifest_digest(manifest)
        release.last_success_commit = data.source_commit.lower()
        release.status = "healthy"
        release.last_error = None
        application.health_status = "healthy"
    except HTTPException:
        raise
    except Exception as exc:
        release.status = "failed"
        release.last_error = str(exc)[:1000]
    runtime.last_seen_at = now
    await db.flush()
    await db.refresh(release)
    return release
